stages:
    - build

variables:
    GIT_SUBMODULE_STRATEGY: normal

build-debian:
    image: registry.videolan.org/vlc-debian-unstable:20200529132440
    stage: build
    tags:
        - docker
        - amd64
    script:
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)

build-macos-x86_64:
    stage: build
    tags:
        - monterey
    script:
        - curl -sS -O https://artifacts.videolan.org/vlc/macos-x86_64/vlc-contrib-x86_64-apple-darwin19-b9001b49855ae2e96274777da57d8da8ad52face.tar.bz2
        - tar xf vlc-contrib-x86_64-apple-darwin19-b9001b49855ae2e96274777da57d8da8ad52face.tar.bz2
        - cd x86_64-apple-darwin19
        - curl -sS -o ./change_prefix.sh 'https://code.videolan.org/videolan/vlc/-/raw/master/contrib/src/change_prefix.sh?inline=false'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - curl -sS -o ./env.build.sh 'https://code.videolan.org/videolan/vlc/-/raw/master/extras/package/macosx/env.build.sh?inline=false'
        - chmod +x ./env.build.sh
        - source ./env.build.sh "contrib"
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`pwd -P`/lib/pkgconfig/"
        - export PATH="$PATH:`pwd -P`/bin/"
        - cd ../
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure
        - make -j $(getconf _NPROCESSORS_ONLN)
        - make install DESTDIR=`pwd`/artifacts
    variables:
        VLC_PATH: /Users/videolanci/sandbox/bin
        VLC_FORCE_KERNELVERSION: 19
        HOST_ARCH: x86_64
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
        paths:
            - build/artifacts/
        expire_in: 1 week

build-win64:
    image: registry.videolan.org/vlc-debian-win64-posix:20241118101328
    stage: build
    tags:
        - docker
        - amd64
    script:
        - wget -nv https://artifacts.videolan.org/vlc/win64/vlc-contrib-x86_64-w64-mingw32-639e528b4c58661401c6c88bc3774b39ab07592e.tar.bz2
        - tar xf vlc-contrib-x86_64-w64-mingw32-639e528b4c58661401c6c88bc3774b39ab07592e.tar.bz2
        - cd x86_64-w64-mingw32
        - wget -nv -O ./change_prefix.sh 'https://code.videolan.org/videolan/vlc/-/raw/master/contrib/src/change_prefix.sh?inline=false'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - cd ..
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`realpath x86_64-w64-mingw32`/lib/pkgconfig/"
        - export PATH="$PATH:`realpath x86_64-w64-mingw32`/bin/"
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure --host=x86_64-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)
        - make install DESTDIR=`pwd`/artifacts
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
        paths:
            - build/artifacts/
        expire_in: 1 week

build-win32:
    image: registry.videolan.org/vlc-debian-llvm-msvcrt:20241118101328
    stage: build
    tags:
        - docker
        - amd64
    script:
        - wget -nv https://artifacts.videolan.org/vlc/win32-llvm/vlc-contrib-i686-w64-mingw32-639e528b4c58661401c6c88bc3774b39ab07592e.tar.bz2
        - tar xf vlc-contrib-i686-w64-mingw32-639e528b4c58661401c6c88bc3774b39ab07592e.tar.bz2
        - cd i686-w64-mingw32
        - wget -nv -O ./change_prefix.sh 'https://code.videolan.org/videolan/vlc/-/raw/master/contrib/src/change_prefix.sh?inline=false'
        - chmod +x ./change_prefix.sh
        - ./change_prefix.sh
        - cd ..
        - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:`realpath i686-w64-mingw32`/lib/pkgconfig/"
        - export PATH="$PATH:`realpath i686-w64-mingw32`/bin/"
        - autoreconf -fisv
        - mkdir build
        - cd build
        - ../configure --host=i686-w64-mingw32
        - make -j $(getconf _NPROCESSORS_ONLN)
        - make install DESTDIR=`pwd`/artifacts
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
        paths:
            - build/artifacts/
        expire_in: 1 week
